--- 
language: generic
sudo: required

jobs:
  include:
    - stage: deploy
      env: TEST_SUITE=none
      install: skip # bundle install is not required
      script:  chmod +x /Product-Content-store-API/deploy.sh
