language: python
python:
    - "3.7"
cache: apt
install:
    - "sudo apt-get install pandoc"

script: python python.py
deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: travistestshibir
    endpoint: aws:s3:::travistestshibir
    region: us-west-2
    skip_cleanup: true
    local-dir: output
    acl: public_read
    detect_encoding: true
notifications:
    email:
        on_failure: always
